services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.6
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181 # Client port
      ZOOKEEPER_TICK_TIME: 2000 # Tick time
      ALLOW_ANONYMOUS_LOGIN: yes # Allow anonymous login
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s
    networks:
      - kafka-network
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data  

  kafka:
    image: confluentinc/cp-kafka:7.4.6
    hostname: kafka
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1 # Unique broker ID
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181' # Zookeeper service
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://<server-ip>:9092 # Change <server-ip> to your server IP
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092 # Listen on all interfaces
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # Only one node
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false" # Disable metrics
      KAFKA_MESSAGE_MAX_BYTES: 2000000000 # 2GB
      KAFKA_REPLICA_FETCH_MAX_BYTES: 2000000000 # 2GB
      KAFKA_REPLICA_MAX_LOG_SIZE: 2000000000 # 2GB
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 168 # Retain logs for 7 days
      KAFKA_LOG_RETENTION_BYTES: 10737418240 # Retain logs for 10 GB
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s
    networks:
      - kafka-network
    volumes:
      - kafka-data:/var/lib/kafka/data  

networks:
  kafka-network:
    driver: bridge

volumes:
  zookeeper-data:
  kafka-data:  